// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3oGW3ypwPdQxGp12v_4LWc32bXXcak5c',
    appId: '1:1053700393154:web:fed5efaec51e22fae2d35b',
    messagingSenderId: '1053700393154',
    projectId: 'appdev-ae8ec',
    authDomain: 'appdev-ae8ec.firebaseapp.com',
    storageBucket: 'appdev-ae8ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97AWj95fMcqvDYFbwu7983globXnrmUI',
    appId: '1:1053700393154:android:bc0716e4481d8baae2d35b',
    messagingSenderId: '1053700393154',
    projectId: 'appdev-ae8ec',
    storageBucket: 'appdev-ae8ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr2GiLUewaUOJZeNTvGRUkGKtHgCBAWtE',
    appId: '1:1053700393154:ios:929cbbf5ad176799e2d35b',
    messagingSenderId: '1053700393154',
    projectId: 'appdev-ae8ec',
    storageBucket: 'appdev-ae8ec.appspot.com',
    iosBundleId: 'com.example.act6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr2GiLUewaUOJZeNTvGRUkGKtHgCBAWtE',
    appId: '1:1053700393154:ios:5f6c91a4a8cf524de2d35b',
    messagingSenderId: '1053700393154',
    projectId: 'appdev-ae8ec',
    storageBucket: 'appdev-ae8ec.appspot.com',
    iosBundleId: 'com.example.act6.RunnerTests',
  );
}
